enterArea.addEventListener('click', handleClickEvent)
allCompaniesBtn.addEventListener('click', fetchCompanies)
allReviewsBtn.addEventListener('click', fetchAllReviews)
allcompaniesBtn.addEventListener('click', fetchCompanies)
allreviewsBtn.addEventListener('click', fetchAllReviews)
document.querySelector("select").addEventListener('change', fetchIndivComp)
